---
- name: config cachingproxy
  hosts: letsencrypt
  handlers:
    - name: Import tasks
      import_tasks: handlers/main.yml
  vars:
    username: cachingproxy
    repo_name: cachingproxy
    service_description: "cachingproxy"
    service_working_dir: ""
    service_script_filename: "start.bash"
  tasks:
  - name: Add user {{ username }}
    become: true
    ansible.builtin.user:
      name: "{{ username }}"
      shell: /bin/bash
  - name: Tasks as user
    become: true
    become_user: "{{ username }}"
    block:
      - name: Checkout source
        ansible.builtin.git:
          repo: "https://github.com/apie/{{ repo_name }}.git"
          dest: "/home/{{ username }}/src"
      - name: Install requirements in venv
        ansible.builtin.pip:
          virtualenv: "/home/{{ username }}/src/venv"
          virtualenv_python: "{{ python_version }}"
          requirements: "/home/{{ username }}/src/requirements.txt"
  - name: copy service file
    become: true
    ansible.builtin.template:
      src: templates/customservice.service.j2
      dest: "/etc/systemd/system/{{ username }}.service"
      mode: 644
    notify:
      - reload systemctl
  - name: enable service + start
    become: true
    ansible.builtin.systemd.service:
      name: "{{ username }}.service"
      state: started
      enabled: yes
  - name: Copy Nginx server configuration locations in place.
    become: true
    template:
      src: templates/cachingproxy.locations.j2
      dest: /etc/nginx/conf.d/{{ inventory_hostname }}.cachingproxy.locations
      mode: 0644
    notify: reload nginx
  - name: Restart service
    become: true
    ansible.builtin.systemd.service:
      name: "{{ username }}.service"
      state: restarted