---
- name: provision vps
  hosts: all
  become: true
  tasks:
  # VPS with Ubuntu 22.04 assumed
  # ansible_user configured, host key login + sudo nopassword
  # Password for ansible_user was changed manually
  # Dns + reverse dns was changed manually
  # Exim4 install + smarthost config + dns change was changed manually
  # Note exim4:
  # dc_readhost='stad.gr'
  - name: Set a hostname
    ansible.builtin.hostname:
      name: "{{ hostname }}"
  - name: Install packages
    package:
      name:
        - unattended-upgrades
        - python3-pip
        - python3-virtualenv
        - acl  # needed for ansible to perform updates as unprivileged users
        - nginx
      state: present
    when: ansible_os_family == 'Debian'
  - name: Set timezone
    community.general.timezone:
      name: Europe/Amsterdam
  - name: Set login banner
    ansible.builtin.copy:
      src: files/banner.txt
      dest: /etc/motd
  - name: Get github.com key
    shell: 'ssh-keyscan -H github.com'
    register: github_key
  - name: Add github.com to known_hosts
    lineinfile:
      dest: /etc/ssh/ssh_known_hosts
      line: "{{ github_key.stdout }}"
