---
- name: config seriesbot
  hosts: all
  tasks:
  - name: Add user seriesbot
    become: true
    ansible.builtin.user:
      name: seriesbot
      shell: /bin/bash
  - name: Tasks as user
    become: true
    become_user: seriesbot
    block:
      - name: Checkout source
        ansible.builtin.git:
          repo: https://github.com/apie/seriesbot.git
          dest: /home/seriesbot/src
      - name: Install requirements locally
        ansible.builtin.pip:
          requirements: /home/seriesbot/src/setup/requirements.txt
      - name: Install telegram-send
        ansible.builtin.pip:
          name: telegram-send
      - name: Setup crontab
        ansible.builtin.cron:
          name: MAILTO
          env: yes
          job: "{{ cron_mailto }}"
      - name: Setup cronjob
        ansible.builtin.cron:
          name: "Send alert for new episodes"
          minute: "1"
          hour: "7"
          job: "/usr/bin/python3.10 /home/seriesbot/src/new_series.py | /home/seriesbot/.local/bin/telegram-send --config /home/seriesbot/src/telegram-send.conf --stdin"
  - name: Load seriesbot + telegram-send config from vault
    include_vars: vault/seriesbot.yml
  - name: Copy seriesbot + telegram-send config from vault
    no_log: true
    become: true
    ansible.builtin.copy:
      content: "{{ item.content }}"
      dest: "/home/seriesbot/src/{{ item.filename }}"
      owner: seriesbot
      group: seriesbot
      mode: 0700
    with_items:
      - "{{ configs }}"

